### ISSUE TITLE
Newlines problem with tabulate

### ISSUE THREAD

**Issue by fpietka** [dbcli/cli_helpers#23]
Right now tabulate do not handle newlines.
Not sure is tabulate is planned to be replaced or if its output should be fixed.

**Comment by tsroten** [comment]
@fpietka Our current tabulate module is a direct copy of tabulate's `master` branch. It's not released on PyPI, yet, so that's why we still have it in CLI Helpers. As soon as the next tabulate is released on PyPI, we'll remove it from CLI Helpers and add it as a requirement.

So, if we want it to support newlines, they we need to address it upstream at https://bitbucket.org/astanin/python-tabulate

**Comment by amjith** [comment]
Tabulate is not the only player anymore. We're also integrating terminaltables which does ship with support for multi-line strings. 

Try changing the `table_format` in your config file to `ascii`

That's the one I use. :)

@fpietka What's the best way to get in touch with you? We're trying to send you an email.

**Comment by fpietka** [comment]
ascii works great indeed, I was wondering about the status on tabulate (if it was going to be dropped or not, since terminaltables works great IMO)

@amjith I got an email from @j-bennet and I did answer it (accepting the invitation). I'm sorry it got lost, but you had my email right.

**Comment by j-bennet** [comment]
@fpietka Got it! thanks for letting us know!

**Comment by badanin-dmitry-playrix** [comment]
Looks like python-tabulate recently got multiline support. https://bitbucket.org/astanin/python-tabulate/commits/cd1a5e590f83f1187bf13ff50cdcf1e250c9fd4a

**Comment by tsroten** [comment]
@badanin-dmitry-playrix Great! Thanks for the heads up. It looks like it isn't released, yet, so we'll keep an eye on it.

**Comment by tsroten** [comment]
Now that CLI Helpers uses tabulate from PyPI, this is fixed :smile:.
